spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: password
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
  application:
    name: products-management-task
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
